version: '3.3'
services:
    v2fly-core:
        container_name: v2fly
        volumes:
            - './v2fly:/etc/v2ray'
        restart: unless-stopped
        image: v2fly/v2fly-core

    frps:
        restart: always
        volumes:
            - './frps/frps.ini:/etc/frp/frps.ini'
        container_name: frps
        image: snowdreamtech/frps

    redis:
        container_name: redis
        image: "redis:alpine"
        restart: unless-stopped
        command: redis-server --save "" --appendonly "no"
        tmpfs:
            - /var/lib/redis
        cap_drop:
            - ALL
        cap_add:
            - SETGID
            - SETUID
            - DAC_OVERRIDE

    search_engine:
        container_name: searxng
        image: searxng/searxng:latest
        restart: unless-stopped
        volumes:
            - './searxng:/etc/searxng:rw'
        environment:
            - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
        cap_drop:
            - ALL
        cap_add:
            - CHOWN
            - SETGID
            - SETUID
            - DAC_OVERRIDE
        logging:
            driver: "json-file"
#         options:
#             max-size: "1m"
#             max-file: "1"


networks:
  default:
    external:
      name: spack.io
